sso:
  realms:
    BCC:
      forgot-username: true
      forgot-password: true
    PCC:
      forgot-username: true
      forgot-password: true
    RCC:
      forgot-username: true
      forgot-password: true
    TTM:
      forgot-username: true
      forgot-password: true
    IHH:
      forgot-username: false
      forgot-password: false

  sessionSharing:
    rules:
      BCC:
        allowFrom: [PCC, RCC]
      PCC:
        allowFrom: [BCC]
      RCC:
        allowFrom: [BCC]
      IHH:
        allowFrom: []
